### ISSUE TITLE
Building dependency tree problem

### ISSUE THREAD

**Issue by willwsharp** [rackerlabs/gradle-jaxb-plugin#12]
Hello,

I want to use your plugin, but I'm having a problem building a dependency tree for my schema.  It relies on some other files that aren't able to be put in the same directory as it; they are just in a jar in a separate location.  Is it possible to tell your plugin to search a given directory if it can't find a dependency in the directory it's currently looking?

Thanks

**Comment by wdschei** [comment]
Have you tried passing them in using the `accessExternalSchema` parameter?

**Comment by wdschei** [comment]
Due to inactivity, this issue is being closed.
