### ISSUE TITLE
Javadoc not fully HTML

### ISSUE THREAD

**Issue by gbesancon** [rackerlabs/gradle-jaxb-plugin#27]
In the javadoc generated for an element the ending > is not converted in its equivalent in html

& lt;complexType name="MyType"> (without space between & and gt/lt;)

expected 

 * & lt;complexType name="MyType"& gt; (without space between & and gt/lt;)

**Comment by wdschei** [comment]
That is interesting. As far as I know, the plugin isn't changing anything being directly produced by JAXB. I wonder if this is a bug over there.

**Comment by wdschei** [comment]
Issue closed due to lack of activity.
