### ISSUE TITLE
Question: Generate .class files from .xsd files

### ISSUE THREAD

**Issue by robachmann** [rackerlabs/gradle-jaxb-plugin#4]
Hi William, I'd like to replace my ant/javac task with this plugin. Is there a possibility to generate .class files from the provided .xsd files? The generated .java files in `build/generated-sources/**.*.java` should be compiled to `build/classes/jaxb`. 

Thank you very much and best regards
Roman

**Comment by wdschei** [comment]
@240ch,

The way my team does this is by adding the `generated-sources` to the Java source directories. Take a look at it here:
 - https://github.com/rackerlabs/repose/blob/master/build.gradle#L202-L227

Kindest regards,
Bill

**Comment by wdschei** [comment]
I'm going to take silence as consent on this one and close it.
