### ISSUE TITLE
how can can I generate different package name for different xsd file?

### ISSUE THREAD

**Issue by stanleyw2014** [rackerlabs/gradle-jaxb-plugin#40]
Hi,
I want to generate different package name for different XSD file(a.xsd->package com.example.a, b.xsd->package com.example.b), I tried to use xsdIncludes, and defined two xjc tasks, but I didn't got what I wanted, below is my xjc tasks:
jaxb {
    xsdDir = "${project.projectDir}/src/main/resources"
    xsdIncludes.add("a.xsd")
    xjc {
        destinationDir = "${project.projectDir}/src/main/java"
        generateEpisodeFiles = false
        taskClassname = "org.jvnet.jaxb2_commons.xjc.XJC2Task"
        generatePackage = "com.example.a"
     
    }
}

jaxb {
    xsdDir = "${project.projectDir}/src/main/resources"
    xsdIncludes.add("b.xsd")
    xjc {
        destinationDir = "${project.projectDir}/src/main/java"
        generateEpisodeFiles = false
        taskClassname = "org.jvnet.jaxb2_commons.xjc.XJC2Task"
        generatePackage = "com.example.b"
  
    }
}

**Comment by wdschei** [comment]
What you appear to be trying to do will require a bindings file. I created a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/) or [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) project for [another issue](https://github.com/rackerlabs/gradle-jaxb-plugin/issues/25) that should give you a better understanding of how to use this feature.

**Comment by wdschei** [comment]
What you appear to be trying to do will require a bindings file. I created a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/) or [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) project for [another issue](https://github.com/rackerlabs/gradle-jaxb-plugin/issues/25) that should give you a better understanding of how to use this feature.

The project can be found [here] (https://github.com/wdschei/gradle-jaxb-plugin_issue25)

**Comment by wdschei** [comment]
What you appear to be trying to do will require a bindings file. I created a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/) or [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) project for [another issue](https://github.com/rackerlabs/gradle-jaxb-plugin/issues/25) that should give you a better understanding of how to use this feature.

The project can be found [here](https://github.com/wdschei/gradle-jaxb-plugin_issue25).

**Comment by stanleyw2014** [comment]
Thanks, William, it works!
