### ISSUE TITLE
Disable episode file generation

### ISSUE THREAD

**Issue by Muselgrusel** [rackerlabs/gradle-jaxb-plugin#6]
Hi,

I would like to disable the generation of episode files but haven't found any hints to achieve that.
If i just missed something please let me know, otherwise it would be great to have such an option in a future release. Thanks for this fork!

Best regards

**Comment by wdschei** [comment]
@Muselgrusel ,

This is a great suggestion. We had a little bit of wiggle room open up in our current sprint and this is now on the books.

* https://repose.atlassian.net/browse/REP-5722

Kindest regards,
Bill

**Comment by wdschei** [comment]
@Muselgrusel ,

This is now live in v2.3.0 of the plugin.

Kindest regards,
Bill
